name: Testjc
favicon: null
layout_spectrum: 0.4968136171810329
typography_spectrum: 0.25804908061400056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3287002930883318
  lightness: 0.21656188857741654
  saturation: 0.15976259391754866
  rhythmicContrast: 0.3461186324711889
purpose: []
